export interface Victim {
  id: string;
  firstName: string;
  lastName: string;
  age: number;
  sex: string;
  hometown: string;
  status: "Deceased" | "Recovering";
  donationLink: string;
  goal: string;
  percentageOfGoal: string;
  websiteCopy: string;
}

export const victims: Victim[] = [
  {
    id: "latasha-polk",
    firstName: "LaTasha",
    lastName: "Polk",
    age: 47,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-lay-latasha-polk-to-rest?qid=7d3c958a9628f0f76faaff6e4f87dd37",
    goal: "$25K",
    percentageOfGoal: "70%",
    websiteCopy: "Latasha Polk's life was tragically lost on New Year's Day due to the terror attack. Latasha has left behind a son, and was a loving wife, child, sister, cousin and friend. She loved to work from sun up to sun down. Her loss is a devastation for the family, and they are asking for help from friends, family, and the community to help lay her to rest."
  },
  {
    id: "edward-pettifer",
    firstName: "Edward",
    lastName: "Pettifer",
    age: 31,
    sex: "M",
    hometown: "London, UK",
    status: "Deceased",
    donationLink: "",
    goal: "",
    percentageOfGoal: "",
    websiteCopy: "Edward was visiting New Orleans for the New Year's Eve holiday. Pettifer's family described him as \"a wonderful son, brother, grandson, nephew and a friend to so many.\" \"We will all miss him terribly,\" the family said in a written statement. \"Our thoughts are with the other families who have lost their family members due to this terrible attack. We request that we can grieve the loss of Ed as a family in private.\""
  },
  {
    id: "brandon-taylor",
    firstName: "Brandon",
    lastName: "Taylor",
    age: 43,
    sex: "M",
    hometown: "Terrytown, LA",
    status: "Deceased",
    donationLink: "",
    goal: "",
    percentageOfGoal: "",
    websiteCopy: "Brandon is remembered as a fun-loving person, full of energy, and high-spirited. Engaged to be married, he was with his fiancee on Bourbon Street celebrating the New Year. To his mother and family he was known as a gentle christian, and to his friends as a lively and creative soul with a deep love for rapping, music, and rapping. Taylor worked as a cook at Dimartino's restaurant in Terrytown. His only brother, Eric Engelhardt, 48, died of a heart attack last year. \"Once I put him to rest, I will have time to cry and cry until I cry it all out,\" his mother said."
  },
  {
    id: "elliot-wilkinson",
    firstName: "Elliot",
    lastName: "Wilkinson",
    age: 40,
    sex: "M",
    hometown: "Slidell, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/aid-for-elliot-wilkinsons-loved-ones?qid=a106558cc71f5b0b44e7911b764ae56f",
    goal: "",
    percentageOfGoal: "",
    websiteCopy: "Elliot loved the city of New Orleans, and he was loved by many he left behind that continue to keep his candle lit on Bourbon. There is also a personal vigil for him on Esplanade. He was a loving, caring guy who touched so many lives during his life. Always joking and laughing and making sure everyone around him had everything they needed. He was a Northshore native that went to Fontainebleau High School and he lived in Covington with his daughter for many years before he moved to New Orleans. Funds are being raised to support his daughter to provide support for school, housing and any other expenses she may incur later in life."
  },
  {
    id: "terry-kennedy",
    firstName: "Terry",
    lastName: "Kennedy",
    age: 63,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/remembering-terrence-life-and-his-legacy?qid=5a515de0a9e86f1299f5d9397422b40e",
    goal: "$13K",
    percentageOfGoal: "12%",
    websiteCopy: "Terrence Kennedy was born and raised in New Orleans as the seventh of nine children to James and Dolores Kennedy. Known for his loving, kind, and jolly nature, Terry had a giant heart and would do anything for anyone, always eager to help those in need. A passionate sports fan, his favorite teams were the New Orleans Saints, Kansas City Chiefs, and his number one team, the Pittsburgh Steelers. He cherished his family, leaving behind two younger sisters and two older brothers, who will forever treasure his memory. The Kennedy family is deeply grateful for all the love, prayers, and support they've received, and they ask for continued prayers for all affected by this tragic event."
  },
  {
    id: "billy-dimaio",
    firstName: "Billy",
    lastName: "DiMaio",
    age: 25,
    sex: "M",
    hometown: "Hoboken, NJ",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/honoring-billy-dimaio-victim-of-new-orleans-terror-attack?qid=ac0921f85f42a00df3d48a801469e0ef",
    goal: "",
    percentageOfGoal: "100%+",
    websiteCopy: "Billy DiMaio, born in East Islip, NY, was a rare soul known for his humility, kindness, humor, and boundless love. He moved to Holmdel, NJ, in 2013 and quickly made an unforgettable impact, forming deep connections with everyone he met. Billy's love for his family was unwavering, especially for his siblings, Samantha and Anthony, and his close bond with his parents, Tracie and his dad. A natural leader and motivator, Billy was a dedicated friend and teammate, always lifting others up, whether on the lacrosse field or at the Jersey Shore, where memories with friends were cherished. Driven by ambition and a determination to succeed, Billy's legacy is one of joy, love, and inspiration, as he continues to bring laughter and warmth to those who loved him."
  },
  {
    id: "drew-dauphin",
    firstName: "Drew",
    lastName: "Dauphin",
    age: 26,
    sex: "M",
    hometown: "Montgomery, AL",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-drew-dauphins-family-through-tragedy?qid=6cd0cafdde341426a821ad29c2735766",
    goal: "$80K",
    percentageOfGoal: "68%",
    websiteCopy: "Drew Dauphin, 26, a native of Montgomery, AL, and a 2023 graduate of Auburn University, tragically lost his life in the New Orleans terrorist attack on New Year's Day. Known for his infectious smile and vibrant personality, Drew had a special way of lighting up every room he entered. His family, who shared an unbreakable bond, reflects that raising him was one of the greatest joys of their lives, and they cherish the 26 years they had with him. Drew found happiness at Lake Martin with his younger brother, Matthew, and a close friend poignantly noted, \"Drew will always now be in the sun at the lake that he loved so much.\" While the family is devastated by this senseless loss, they remain forever grateful for the time they shared and are relying on the support of loved ones as they navigate this heartbreaking tragedy."
  },
  {
    id: "matthew-tenedorio",
    firstName: "Matthew",
    lastName: "Tenedorio",
    age: 25,
    sex: "M",
    hometown: "Picayune, MS",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/matthew-tenedorio-new-orleans-terror-attack-victim?qid=ee5576c139fa46b7a053dbe27caa085c",
    goal: "$35K",
    percentageOfGoal: "100%+",
    websiteCopy: "On January 1, 2025, Matthew's family's lives were forever altered by his tragic loss. A beloved son, brother, uncle, and friend, Matthew's laid-back spirit and infectious laughter brought joy to everyone he encountered. As an audiovisual technician for the Superdome, he played a vital role in creating unforgettable experiences for fans and event-goers. Matthew graduated from Pearl River Central High School, where he made lasting friendships and was known for his ability to lighten the mood and spread positivity. Survived by his parents Lou and Cathy, his siblings Jonathon and Jeremy, and his cherished niece and nephews, Matthew's loss has left an irreplaceable void in the hearts of his family and friends, who are now seeking support to cover his funeral expenses during this incredibly difficult time."
  },
  {
    id: "nikyra-cheyenne-dedeaux",
    firstName: "Ni'kyra \"Cheyenne\"",
    lastName: "Dedeaux",
    age: 18,
    sex: "F",
    hometown: "Gulfport, MS",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-us-honor-nikyra-cheyenne?qid=af36ac19f0682d89028baf988ad82776",
    goal: "$4K",
    percentageOfGoal: "0%",
    websiteCopy: "Ni'Kyra \"Cheyenne\" Dedeaux, a beloved daughter, friend, and aspiring nurse, was known for her bright spirit and her ability to bring joy to those around her. Described as a \"little ball of sunshine,\" Cheyenne was always surrounded by friends, whether she was working, hanging out with her girls, or cheering up anyone who needed a boost. A proud graduate (2024) of Harrison Central High School in Gulfport, Mississippi, Cheyenne was set to begin a nursing program at Blue Cliff College in January 2025, following in the footsteps of her mother, a fellow nurse. Thought of as a \"momma's girl\" and a \"daddy's girl,\" Cheyenne's positive attitude and intelligence shone through in everything she did, never letting any negative moments linger. Known by the nickname \"Biscuit,\" Cheyenne's friends and family will forever remember her for her warmth, kindness, and unwavering optimism."
  },
  {
    id: "reggie-hunter",
    firstName: "Reggie",
    lastName: "Hunter",
    age: 37,
    sex: "M",
    hometown: "Prairieville, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-us-honor-reggie-hunters-memory?qid=7c717b6533018da8a6e6073af5ec1c17",
    goal: "$45K",
    percentageOfGoal: "100%+",
    websiteCopy: "Hunter was born in California but spent most of his life in the Baton Rouge and Independence areas, where he worked as a warehouse manager for the past six years. A proud member of the Zulu Social Aid & Pleasure Club, he had plans to attend the club's ball before his tragic passing. Hunter took great pride in his 12-year-old son's academic achievements in the STEM field and adored his 18-month-old son. He loved working out with family and friends, often joking about getting \"swole\" at the gym with his cousins and homeboys. Known for his love of fashion, Hunter was a self-proclaimed \"city slicker,\" always making sure his tennis shoes matched his hat and enjoying the finer things."
  },
  {
    id: "tiger-bech",
    firstName: "Tiger",
    lastName: "Bech",
    age: 27,
    sex: "M",
    hometown: "New York, NY",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/supporting-ryan-quigleys-recovery-and-honoring-tiger-bech",
    goal: "",
    percentageOfGoal: "",
    websiteCopy: "Tiger Bech was a one-of-a-kind athlete, known for his incredible ability on the football field, where he collected 1,646 total yards and 19 touchdowns during his standout high school career at St. Thomas More in 2014. A first-team All-District and All-Acadiana performer, Bech was not only a versatile football player but also a standout lacrosse player, leaving a lasting impression as a special talent and human being. After graduating from STM, Bech completed a postgraduate year at The Loomis-Chaffee School before heading to Princeton University, where he was a starting wide receiver and punt return specialist, earning numerous All-Ivy honors. Graduating with a degree in finance in 2021, he worked in cybersecurity, trading, and eventually as an analyst at Seaport Global in New York City, where he pursued his dream job in finance. Beyond his athletic abilities, Tiger's deep personality, maturity, and connection with others left a lasting impact on everyone who knew him."
  },
  {
    id: "nicole-perez",
    firstName: "Nicole",
    lastName: "Perez",
    age: 27,
    sex: "F",
    hometown: "Metairie, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-cover-burial-costs-for-bourbon-st-victim?qid=5cfb0cd3a3836d374c67e21ed5ca4f78",
    goal: "$50K",
    percentageOfGoal: "100%+",
    websiteCopy: "Nicole Perez, a 27-year-old mother from Metairie, was tragically killed in the New Year's Day Bourbon Street attack just after receiving a promotion to manager at the deli where she worked. In addition to her career, Perez was focused on her 5-year-old son, teaching him to read and do math, and was preparing to move into a new apartment. Despite facing recent hardships, she remained dedicated to her job and motivated by her love for her son, walking to work at 5:30 a.m. to ensure she was on time. Her boss, Kimberly Usher, described her as a fast learner who was deeply committed to her success and her family. \"She was a good mom,\" Usher said, remembering Perez's drive and determination to build a better future."
  },
  {
    id: "kareem-badawi",
    firstName: "Kareem",
    lastName: "Badawi",
    age: 18,
    sex: "M",
    hometown: "Baton Rouge, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/kareem-badawis-legacy?qid=62d605d8b9d80ae237f40652f033e5cd",
    goal: "$100K",
    percentageOfGoal: "35%",
    websiteCopy: "Kareem Badawi, a beloved member of the Baton Rouge Episcopal School community, was known for his selflessness, carefree spirit, and dedication to others. A standout on the school's football team, he was described by his coach, Travis Bourgeois, as someone who always put others before himself, with a deep love for his family and friends. Kareem graduated from Episcopal in 2024 and went on to attend the University of Alabama, where he shared a close friendship with Ethan Ott, who described him as outgoing and always eager to make people happy. An aspiring engineer, Kareem excelled both academically and athletically, playing football, baseball, and basketball, and becoming a pledge of Sigma Chi fraternity. He is leaving behind a legacy of kindness, warmth, and a tight-knit group of friends and family who will forever remember him."
  },
  {
    id: "hubert-gauthreaux",
    firstName: "Hubert",
    lastName: "Gauthreaux",
    age: 21,
    sex: "M",
    hometown: "Gretna, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/honor-hubert-gauthreaux?qid=121594959bfc5b6e5365e3e5994bf5be",
    goal: "$30K",
    percentageOfGoal: "100%+",
    websiteCopy: "Hubert Gauthreaux, 21, was a young man living a quintessential Louisianan life, working an oil services job and cherishing time with his close-knit family in Gretna. Known for his love of the Chicago White Sox, Hubert had a passion for fashion and was always striving to improve his style. His sister, Brooke, described him as her \"sweet, selfless baby brother,\" expressing deep grief at his untimely death and how much he meant to her. Hubert was a \"classy kid\" who took pride in looking out for his loved ones, always there for his family and friends. His memory lives on as a devoted son, brother, and friend, forever remembered for his warmth, loyalty, and love of life."
  },
  {
    id: "lenny-mcclain",
    firstName: "Lenny",
    lastName: "McClain",
    age: 29,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/donate-to-lenny-mcclains-healing-journey",
    goal: "$13K",
    percentageOfGoal: "3%",
    websiteCopy: "Lenny McClain, one of the 30 victims of the January 1st \"Bourbon Street Attack\" in New Orleans, is currently in ICU at Ochsner's Hospital, recovering from severe injuries. The eldest of seven siblings, Lenny has always been a source of guidance and support for his family, with a passion for singing that brought him joy. Employed by Popeyes Chicken and Biscuits in New Orleans, Lenny has lost his only source of income and will need financial help for food, rent, medical supplies, transportation, and other essential expenses, as he has no medical insurance. His family is praying for a full recovery, but they are uncertain when he will be able to return to work or resume his normal life. Any donations to assist with Lenny's immediate and future needs are greatly appreciated, and the family is deeply grateful for the support during this difficult time."
  },
  {
    id: "adam-coste",
    firstName: "Adam",
    lastName: "Coste",
    age: 0,
    sex: "M",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/assist-adam-a-brave-veteran-in-healing?qid=efbe98f1fa8ede3b1b59b05558e0f4f7",
    goal: "$100K",
    percentageOfGoal: "92%",
    websiteCopy: "Adam Coste was a victim of the New Year's Day Bourbon Street terror attack, suffering severe injuries to his lower extremities after being struck by a vehicle. He is currently receiving treatment at a New Orleans hospital and will require multiple surgeries and rehabilitation to regain his ability to walk. A devoted friend, military veteran, and passionate educator, Adam served as a U.S. Army Infantry Company Commander and later as an Assistant Professor of Military Science at Tulane University. Currently working as the Educational Travel Manager at the National WWII Museum, Adam is dedicated to studying and teaching military history, but now faces the challenge of recovering physically and financially. This GoFundMe, organized by his close friend Scott Hedge, will help cover Adam's medical and living expenses, with any excess funds being donated to the Greater New Orleans Foundation as Adam wishes."
  },
  {
    id: "jeremi-senski",
    firstName: "Jeremi",
    lastName: "Senski",
    age: 0,
    sex: "M",
    hometown: "Washington, PA",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/support-jeremis-recovery-after-tragic-terror-attack?qid=efbe98f1fa8ede3b1b59b05558e0f4f7",
    goal: "$75K",
    percentageOfGoal: "64%",
    websiteCopy: "Jeremi Senski, a quadriplegic for 25 years, was caught in the Bourbon Street attack chaos, thrown from his wheelchair and left helpless on the street. After hours of uncertainty, his family finally found him alive in the ICU after undergoing a 10+ hour surgery for broken bones. Despite his critical condition, he is a fighter with an incredible will to live, but his long recovery will be costly. His family is asking for financial support to help cover the unexpected expenses of his medical care, wheelchair replacement, and additional costs for our stay in New Orleans as they care for him through this journey. Any help would be deeply appreciated, and they are committed to paying this generosity forward in the future."
  },
  {
    id: "george-walker",
    firstName: "George",
    lastName: "Walker",
    age: 0,
    sex: "M",
    hometown: "Westwego",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/aid-for-a-father-after-bourbon-street-tragedy?qid=5a515de0a9e86f1299f5d9397422b40e",
    goal: "$5K",
    percentageOfGoal: "4%",
    websiteCopy: "George is a 31 year old single father of 3. He is a New Orleans native, who was the victim of the January 1st New Years, Bourbon Street terrorist attack. All the donations will be simply used to cover medical expenses and living costs until he is able to work again."
  },
  {
    id: "tommy-williams",
    firstName: "Tommy",
    lastName: "Williams",
    age: 0,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/Help-tommy-williams-heal-after-tragic-incident?qid=5a515de0a9e86f1299f5d9397422b40e",
    goal: "$9K",
    percentageOfGoal: "26%",
    websiteCopy: "Tommy Williams was a victim of the Bourbon Street incident, suffering a cracked skull, broken leg, and lung injury while saving a family member from being hit by the truck. He has undergone two surgeries, including the insertion of a rod in his shattered tibia, and is facing a long recovery with both physical and mental challenges. As a hands-on father to two young sons, this tragedy has left them without their active, supportive dad. The family is seeking assistance to help cover medical expenses, transportation, and daily needs as Tommy faces a difficult road ahead. Any support during this time of need would be deeply appreciated."
  },
  {
    id: "laquana-sheppard",
    firstName: "Laquana",
    lastName: "Sheppard",
    age: 0,
    sex: "F",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/aid-laquana-sheppards-healing-journey?qid=5a515de0a9e86f1299f5d9397422b40e",
    goal: "$9K",
    percentageOfGoal: "88%",
    websiteCopy: "Laquana Sheppard was a victim of the Bourbon Street terrorist attack on New Year's and is currently in the hospital recovering from severe injuries. As a dedicated school teacher and devoted mother, her injuries prevent her from returning to work and supporting her family. Her sister is raising funds to help cover living expenses during this critical recovery period. The funds will go directly to Laquana to help maintain stability while she heals. Any donation or sharing of her story is greatly appreciated by the family."
  },
  {
    id: "kevin-curry",
    firstName: "Kevin",
    lastName: "Curry",
    age: 0,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/help-kevin-curry-heal-after-new-orleans-tragic-attack?qid=5a515de0a9e86f1299f5d9397422b40e",
    goal: "$10K",
    percentageOfGoal: "54%",
    websiteCopy: "On January 1, 2025, Kevin Curry was tragically injured in the terrorist attack on Bourbon Street in New Orleans. He and his cousin, Reggie Hunter, were together when the attack occurred, with Reggie fatally injured and Kevin sustaining serious injuries from being struck by the attacker's truck. Kevin is currently stable, having undergone the first of many necessary surgeries, but he faces a long road to recovery with ongoing medical care and rehabilitation. His family is seeking support to help cover the growing costs of his treatment and recovery expenses. Any contribution, no matter the amount, is deeply appreciated as Kevin continues his healing journey."
  },
  {
    id: "parker-vindrine",
    firstName: "Parker",
    lastName: "Vindrine",
    age: 18,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/support-parker-vidrines-recovery-from-terrorist-attack?qid=6cd0cafdde341426a821ad29c2735766",
    goal: "$50K",
    percentageOfGoal: "80%",
    websiteCopy: "Parker Vidrine, an 18-year-old freshman at Ole Miss, was critically injured in the terrorist attack on Bourbon Street on January 1, 2025. What was meant to be a celebratory night with friends turned into a tragedy when Parker was struck by a truck, alongside his friend Kareem Badawi, who tragically lost his life. Parker underwent emergency surgery and was placed on a ventilator, and after several days in the ICU, he is now home but still faces a long road to recovery. His family, including his mother Andrea and sister Kaitlyn, are by his side, providing love and support as they cope with the overwhelming financial burden of his medical care. Funds raised will go directly to Parker and his family to help cover medical expenses and recovery costs during this difficult time."
  },
  {
    id: "emile-luui-graham",
    firstName: "Emile \"Luui\"",
    lastName: "Graham",
    age: 0,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/ROADTORWCOVERY?qid=6cd0cafdde341426a821ad29c2735766",
    goal: "$40K",
    percentageOfGoal: "86%",
    websiteCopy: "Carmela Graham's 23-year-old son, Emile (Luui), was critically injured in the terrorist attack on Bourbon Street on January 1, 2025. After being struck by the attacker's vehicle, Emile was found bleeding in the street and was saved by a heroic woman who used a tourniquet to keep him alive until EMS arrived. Emile suffered multiple fractures, including a broken femur that tore through his femoral artery, requiring immediate surgery. Following a lengthy 7.5-hour surgery, he will need additional surgeries and extensive physical therapy as he recovers. His family is seeking financial assistance to cover medical expenses, home equipment, and ongoing care during his long road to recovery."
  },
  {
    id: "cynsere-anderson",
    firstName: "Cynsere",
    lastName: "Anderson",
    age: 0,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/vsf33g-support-for-healing-after-tragic-loss?qid=6cd0cafdde341426a821ad29c2735766",
    goal: "$12K",
    percentageOfGoal: "10%",
    websiteCopy: "Julienne is raising funds for her sister Cynsere, who survived the January 1, 2025, terrorist attack on Bourbon Street that tragically claimed the life of her close friend Nicole. Cynsere was struck by the attacker's truck, leaving her with severe physical injuries, and she is now dealing with PTSD from witnessing Nicole's death and the traumatic events. Unable to work due to her injuries, Cynsere is struggling to care for her 10-month-old son and is in need of both physical and mental therapy. The emotional toll is compounded by the viral video of the attack, which she must relive daily. Donations will support her recovery and help provide for her son during this difficult time, as she works to heal from both the physical and emotional scars of the attack."
  },
  {
    id: "alexis-scott-windham",
    firstName: "Alexis",
    lastName: "Scott-Windham",
    age: 23,
    sex: "F",
    hometown: "Mobile, AL",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/help-support-alexis-scott-windham-after-new-orleans-tragedy?qid=13809cda87d8d50026c28f2626cb45e8",
    goal: "$16K",
    percentageOfGoal: "87%",
    websiteCopy: "Alexis Scott Windham, a 23-year-old from Mobile, AL, is a survivor of the January 1, 2025, terrorist attack in New Orleans. She was shot in the foot and struck by the suspect's truck, resulting in multiple fractures and a bullet still lodged in her foot. Unable to work and provide for herself and her one-year-old daughter, Alexis is seeking financial support during her difficult recovery. She is also seeking emotional and physical therapy to heal from the trauma of the attack. Alexis is asking for help to support her and her child as she navigates this challenging time."
  },
  {
    id: "zion-parsons",
    firstName: "Zion",
    lastName: "Parsons",
    age: 0,
    sex: "",
    hometown: "Gulfport, MS",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/c/act/how-to-help-attack-in-new-orleans",
    goal: "$2.4K",
    percentageOfGoal: "50%",
    websiteCopy: "Chaniece Parsons is raising funds for her son, Zion Parsons, who was a victim of the New Orleans terrorist attack that claimed many lives, including a friend. Zion is struggling with signs of PTSD and will need therapy and counseling to cope with the traumatic experiences he witnessed. While his therapy will be covered, the family still requires financial support to cover additional recovery expenses as Zion works towards returning to work. Any help would be greatly appreciated as they navigate this difficult time. The family is also grateful for the prayers and support from around the world during their recovery."
  },
  {
    id: "ryan-quigley",
    firstName: "Ryan",
    lastName: "Quigley",
    age: 0,
    sex: "",
    hometown: "",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/supporting-ryan-quigleys-recovery-and-honoring-tiger-bech",
    goal: "",
    percentageOfGoal: "",
    websiteCopy: "On January 1, 2025, a tragic attack in New Orleans changed the lives of two young men, Ryan Quigley and his close friend Tiger Bech. Tiger lost his life in the attack, while Ryan is now undergoing treatment and beginning his road to recovery. Funds were raised to assist Tiger's family with funeral costs and support Ryan with his medical expenses. Ryan's loved ones are rallying around him as he faces this challenging journey. The goal is to honor Tiger's memory by easing the financial burden on his family during this heartbreaking time."
  },
  {
    id: "corian-evans",
    firstName: "Corian",
    lastName: "Evans",
    age: 21,
    sex: "F",
    hometown: "Mobile, LA",
    status: "Recovering",
    donationLink: "https://www.gofundme.com/f/aid-corians-healing-from-new-years-attack",
    goal: "$2K",
    percentageOfGoal: "75%",
    websiteCopy: "Corian Evans, a 21-year-old criminal justice major at the University of South Alabama from Mobile, AL, is a survivor of the New Year's Day attack in New Orleans. During the attack, a truck struck her, causing a fractured foot and several bruises. Mentally and physically traumatized, Corian is unable to work or attend classes as she recovers, which will take 4-8 weeks. In addition to medical expenses, she plans to seek therapy for the trauma she's experienced, as she struggles with constant flashbacks and difficulty eating and sleeping. Corian's heart goes out to the families of those who lost their lives in the attack."
  }
]; 