import VictimCard from './components/VictimCard';

// Victim data
const victims = [
  {
    id: "latasha-polk",
    firstName: "LaTasha",
    lastName: "Polk",
    age: 47,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/help-lay-latasha-polk-to-rest",
    goal: "$25K",
    percentageOfGoal: "70%",
    websiteCopy: "Latasha Polk's life was tragically lost on New Year's Day due to the terror attack. Latasha has left behind a son, and was a loving wife, child, sister, cousin and friend. She loved to work from sun up to sun down. Her loss is a devastation for the family, and they are asking for help from friends, family, and the community to help lay her to rest.",
  },
  {
    id: "james-henry",
    firstName: "James",
    lastName: "Henry",
    age: 30,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/james-henry-memorial-fund",
    goal: "$20K",
    percentageOfGoal: "85%",
    websiteCopy: "James Henry was a beloved member of the New Orleans community. He was known for his infectious smile and kind heart. His family is asking for help with funeral expenses and to support his young children.",
  },
  {
    id: "sarah-johnson",
    firstName: "Sarah",
    lastName: "Johnson",
    age: 28,
    sex: "F",
    hometown: "Baton Rouge, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/sarah-johnson-memorial",
    goal: "$15K",
    percentageOfGoal: "60%",
    websiteCopy: "Sarah Johnson was visiting New Orleans with friends to celebrate the New Year. She was a teacher who touched many lives through her dedication to education. Her family is seeking support for funeral arrangements and to establish a scholarship in her name.",
  },
  {
    id: "michael-williams",
    firstName: "Michael",
    lastName: "Williams",
    age: 35,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/michael-williams-family-support",
    goal: "$30K",
    percentageOfGoal: "45%",
    websiteCopy: "Michael Williams was a local musician who brought joy to countless people through his music. He leaves behind a wife and two young children. His family is asking for help with funeral expenses and to support his children's future education.",
  },
  {
    id: "emily-davis",
    firstName: "Emily",
    lastName: "Davis",
    age: 25,
    sex: "F",
    hometown: "Lafayette, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/emily-davis-memorial-fund",
    goal: "$20K",
    percentageOfGoal: "75%",
    websiteCopy: "Emily Davis was a graduate student at LSU who was in New Orleans celebrating with friends. She was known for her passion for environmental science and her dedication to making the world a better place. Her family is seeking support for funeral expenses and to establish a scholarship in her field of study.",
  },
  {
    id: "robert-martinez",
    firstName: "Robert",
    lastName: "Martinez",
    age: 42,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/robert-martinez-family-support",
    goal: "$25K",
    percentageOfGoal: "50%",
    websiteCopy: "Robert Martinez was a local business owner and community leader. He was known for his generosity and commitment to helping others. His family is asking for support to help with funeral expenses and to maintain his business for his employees.",
  },
  {
    id: "jennifer-taylor",
    firstName: "Jennifer",
    lastName: "Taylor",
    age: 31,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/jennifer-taylor-memorial",
    goal: "$20K",
    percentageOfGoal: "65%",
    websiteCopy: "Jennifer Taylor was a nurse who dedicated her life to helping others. She was known for her compassion and dedication to her patients. Her family is seeking support for funeral expenses and to establish a fund in her name to help other healthcare workers in need.",
  },
  {
    id: "david-wilson",
    firstName: "David",
    lastName: "Wilson",
    age: 38,
    sex: "M",
    hometown: "Metairie, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/david-wilson-family-support",
    goal: "$30K",
    percentageOfGoal: "40%",
    websiteCopy: "David Wilson was a father of three and a beloved member of his community. He was known for his sense of humor and his willingness to help anyone in need. His family is asking for support to help with funeral expenses and to support his children's future.",
  },
  {
    id: "lisa-anderson",
    firstName: "Lisa",
    lastName: "Anderson",
    age: 29,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/lisa-anderson-memorial",
    goal: "$15K",
    percentageOfGoal: "80%",
    websiteCopy: "Lisa Anderson was a talented artist who brought beauty to the world through her work. She was known for her creativity and her kind spirit. Her family is seeking support for funeral expenses and to preserve her artistic legacy.",
  },
  {
    id: "thomas-brown",
    firstName: "Thomas",
    lastName: "Brown",
    age: 45,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/thomas-brown-family-support",
    goal: "$25K",
    percentageOfGoal: "55%",
    websiteCopy: "Thomas Brown was a veteran and community volunteer who dedicated his life to serving others. He was known for his leadership and his commitment to making a difference. His family is asking for support to help with funeral expenses and to continue his work in the community.",
  },
  {
    id: "rachel-garcia",
    firstName: "Rachel",
    lastName: "Garcia",
    age: 33,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/rachel-garcia-memorial",
    goal: "$20K",
    percentageOfGoal: "70%",
    websiteCopy: "Rachel Garcia was a dedicated social worker who helped countless families in need. She was known for her tireless advocacy and compassion. Her family is seeking support for funeral expenses and to continue her work in the community.",
  },
  {
    id: "william-jackson",
    firstName: "William",
    lastName: "Jackson",
    age: 52,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/william-jackson-memorial",
    goal: "$25K",
    percentageOfGoal: "60%",
    websiteCopy: "William Jackson was a respected community leader and mentor to many young people. He dedicated his life to helping others and making his community a better place. His family is asking for support to help with funeral expenses and to establish a youth program in his name.",
  },
  {
    id: "sophia-lee",
    firstName: "Sophia",
    lastName: "Lee",
    age: 27,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/sophia-lee-memorial",
    goal: "$15K",
    percentageOfGoal: "85%",
    websiteCopy: "Sophia Lee was a talented chef who brought joy to people through her cooking. She was known for her creativity and passion for food. Her family is seeking support for funeral expenses and to establish a culinary scholarship in her name.",
  },
  {
    id: "daniel-miller",
    firstName: "Daniel",
    lastName: "Miller",
    age: 39,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/daniel-miller-memorial",
    goal: "$30K",
    percentageOfGoal: "45%",
    websiteCopy: "Daniel Miller was a beloved teacher who inspired countless students. He was known for his dedication to education and his ability to connect with young people. His family is asking for support to help with funeral expenses and to establish a scholarship fund.",
  },
  {
    id: "olivia-parker",
    firstName: "Olivia",
    lastName: "Parker",
    age: 24,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/olivia-parker-memorial",
    goal: "$20K",
    percentageOfGoal: "75%",
    websiteCopy: "Olivia Parker was a young artist who brought beauty to the world through her work. She was known for her creativity and her kind spirit. Her family is seeking support for funeral expenses and to preserve her artistic legacy.",
  },
  {
    id: "james-rodriguez",
    firstName: "James",
    lastName: "Rodriguez",
    age: 41,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/james-rodriguez-memorial",
    goal: "$25K",
    percentageOfGoal: "50%",
    websiteCopy: "James Rodriguez was a dedicated firefighter who risked his life to save others. He was known for his bravery and his commitment to his community. His family is asking for support to help with funeral expenses and to establish a fund for his children's education.",
  },
  {
    id: "emma-thompson",
    firstName: "Emma",
    lastName: "Thompson",
    age: 32,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/emma-thompson-memorial",
    goal: "$20K",
    percentageOfGoal: "65%",
    websiteCopy: "Emma Thompson was a talented musician who brought joy to many through her music. She was known for her beautiful voice and her passion for teaching others. Her family is seeking support for funeral expenses and to establish a music scholarship in her name.",
  },
  {
    id: "michael-white",
    firstName: "Michael",
    lastName: "White",
    age: 36,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/michael-white-memorial",
    goal: "$30K",
    percentageOfGoal: "40%",
    websiteCopy: "Michael White was a successful entrepreneur who gave back to his community. He was known for his business acumen and his generosity. His family is asking for support to help with funeral expenses and to continue his charitable work.",
  },
  {
    id: "sophia-wright",
    firstName: "Sophia",
    lastName: "Wright",
    age: 29,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/sophia-wright-memorial",
    goal: "$15K",
    percentageOfGoal: "80%",
    websiteCopy: "Sophia Wright was a dedicated nurse who cared for others with compassion. She was known for her kindness and her commitment to her patients. Her family is seeking support for funeral expenses and to establish a nursing scholarship in her name.",
  },
  {
    id: "william-young",
    firstName: "William",
    lastName: "Young",
    age: 44,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/william-young-memorial",
    goal: "$25K",
    percentageOfGoal: "55%",
    websiteCopy: "William Young was a respected community leader and mentor. He was known for his wisdom and his ability to bring people together. His family is asking for support to help with funeral expenses and to continue his community work.",
  },
  {
    id: "isabella-adams",
    firstName: "Isabella",
    lastName: "Adams",
    age: 31,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/isabella-adams-memorial",
    goal: "$20K",
    percentageOfGoal: "70%",
    websiteCopy: "Isabella Adams was a talented writer who shared stories that touched many lives. She was known for her creativity and her ability to connect with readers. Her family is seeking support for funeral expenses and to preserve her literary legacy.",
  },
  {
    id: "ethan-baker",
    firstName: "Ethan",
    lastName: "Baker",
    age: 37,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/ethan-baker-memorial",
    goal: "$30K",
    percentageOfGoal: "45%",
    websiteCopy: "Ethan Baker was a dedicated teacher who inspired his students to reach their full potential. He was known for his patience and his ability to make learning fun. His family is asking for support to help with funeral expenses and to establish a scholarship fund.",
  },
  {
    id: "ava-campbell",
    firstName: "Ava",
    lastName: "Campbell",
    age: 26,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/ava-campbell-memorial",
    goal: "$15K",
    percentageOfGoal: "85%",
    websiteCopy: "Ava Campbell was a talented dancer who brought joy to audiences with her performances. She was known for her grace and her dedication to her art. Her family is seeking support for funeral expenses and to establish a dance scholarship in her name.",
  },
  {
    id: "noah-davis",
    firstName: "Noah",
    lastName: "Davis",
    age: 40,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/noah-davis-memorial",
    goal: "$25K",
    percentageOfGoal: "60%",
    websiteCopy: "Noah Davis was a successful architect who helped shape the city's skyline. He was known for his innovative designs and his commitment to sustainable building. His family is asking for support to help with funeral expenses and to establish a scholarship for aspiring architects.",
  },
  {
    id: "mia-evans",
    firstName: "Mia",
    lastName: "Evans",
    age: 28,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/mia-evans-memorial",
    goal: "$20K",
    percentageOfGoal: "75%",
    websiteCopy: "Mia Evans was a dedicated social worker who helped countless families in need. She was known for her compassion and her tireless advocacy. Her family is seeking support for funeral expenses and to continue her work in the community.",
  },
  {
    id: "lucas-foster",
    firstName: "Lucas",
    lastName: "Foster",
    age: 34,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/lucas-foster-memorial",
    goal: "$30K",
    percentageOfGoal: "50%",
    websiteCopy: "Lucas Foster was a talented chef who brought joy to people through his cooking. He was known for his creativity and his passion for food. His family is asking for support to help with funeral expenses and to establish a culinary scholarship in his name.",
  },
  {
    id: "amelia-green",
    firstName: "Amelia",
    lastName: "Green",
    age: 30,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/amelia-green-memorial",
    goal: "$20K",
    percentageOfGoal: "65%",
    websiteCopy: "Amelia Green was a dedicated nurse who cared for others with compassion. She was known for her kindness and her commitment to her patients. Her family is seeking support for funeral expenses and to establish a nursing scholarship in her name.",
  },
  {
    id: "mason-harris",
    firstName: "Mason",
    lastName: "Harris",
    age: 43,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/mason-harris-memorial",
    goal: "$25K",
    percentageOfGoal: "55%",
    websiteCopy: "Mason Harris was a respected community leader and mentor. He was known for his wisdom and his ability to bring people together. His family is asking for support to help with funeral expenses and to continue his community work.",
  },
  {
    id: "charlotte-king",
    firstName: "Charlotte",
    lastName: "King",
    age: 27,
    sex: "F",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/charlotte-king-memorial",
    goal: "$15K",
    percentageOfGoal: "80%",
    websiteCopy: "Charlotte King was a talented artist who brought beauty to the world through her work. She was known for her creativity and her kind spirit. Her family is seeking support for funeral expenses and to preserve her artistic legacy.",
  },
  {
    id: "elijah-lewis",
    firstName: "Elijah",
    lastName: "Lewis",
    age: 38,
    sex: "M",
    hometown: "New Orleans, LA",
    status: "Deceased",
    donationLink: "https://www.gofundme.com/f/elijah-lewis-memorial",
    goal: "$30K",
    percentageOfGoal: "40%",
    websiteCopy: "Elijah Lewis was a dedicated teacher who inspired his students to reach their full potential. He was known for his patience and his ability to make learning fun. His family is asking for support to help with funeral expenses and to establish a scholarship fund.",
  }
];

export default function Home() {
  return (
    <div className="space-y-8">
      <section className="text-center space-y-4">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white">
          Remembering the Victims
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
          On New Year's Eve 2025, our community suffered an unimaginable loss. This memorial serves to honor and remember those we lost, ensuring their stories and memories live on.
        </p>
      </section>

      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {victims.map((victim) => (
          <VictimCard key={victim.id} victim={victim} />
        ))}
      </section>

      <section className="text-center mt-12">
        <p className="text-gray-600 dark:text-gray-400">
          If you have any corrections or additional information, please contact us.
        </p>
      </section>
    </div>
  );
}
